// 하드코딩 맞춤법 교정 함수 (확장 버전)
// 사람들이 자주 틀리는 맞춤법, 오타, 띄어쓰기, 관용적 오류 등 50개 이상 포함

/**
 * 자주 틀리는 맞춤법/오타/띄어쓰기 하드코딩 교정 (확장)
 * @param {string} text - 교정할 텍스트
 * @returns {string} - 교정된 텍스트
 */
export function spellHardcodedFix(text) {
  if (!text || typeof text !== 'string') return text;
  return text
    // '됬다' → '됐다'
    .replace(/됬다/g, '됐다')
    // '됬어' → '됐어'
    .replace(/됬어/g, '됐어')
    // '됬습니다' → '됐습니다'
    .replace(/됬습니다/g, '됐습니다')
    // '안됬다' → '안됐다'
    .replace(/안됬다/g, '안됐다')
    // '안됬어' → '안됐어'
    .replace(/안됬어/g, '안됐어')
    // '안됬습니다' → '안됐습니다'
    .replace(/안됬습니다/g, '안됐습니다')
    // '않되' → '안돼'
    .replace(/않되/g, '안돼')
    // '되요' → '돼요'
    .replace(/되요/g, '돼요')
    // '되서' → '돼서'
    .replace(/되서/g, '돼서')
    // '되었다' → '됐다'
    .replace(/되었다/g, '됐다')
    // '되었다고' → '됐다고'
    .replace(/되었다고/g, '됐다고')
    // '되었다면' → '됐다면'
    .replace(/되었다면/g, '됐다면')
    // '되었으면' → '됐으면'
    .replace(/되었으면/g, '됐으면')
    // '되었을' → '됐을'
    .replace(/되었을/g, '됐을')
    // '되었으니' → '됐으니'
    .replace(/되었으니/g, '됐으니')
    // '않된다' → '안된다'
    .replace(/않된다/g, '안된다')
    // '않돼' → '안돼'
    .replace(/않돼/g, '안돼')
    // '않됬' → '안됐'
    .replace(/않됬/g, '안됐')
    // '않됬다' → '안됐다'
    .replace(/않됬다/g, '안됐다')
    // '않됬어' → '안됐어'
    .replace(/않됬어/g, '안됐어')
    // '않됬습니다' → '안됐습니다'
    .replace(/않됬습니다/g, '안됐습니다')
    // '않되요' → '안돼요'
    .replace(/않되요/g, '안돼요')
    // '않되서' → '안돼서'
    .replace(/않되서/g, '안돼서')
    // '않되었다' → '안됐다'
    .replace(/않되었다/g, '안됐다')
    // '않되었다고' → '안됐다고'
    .replace(/않되었다고/g, '안됐다고')
    // '않되었다면' → '안됐다면'
    .replace(/않되었다면/g, '안됐다면')
    // '않되었으면' → '안됐으면'
    .replace(/않되었으면/g, '안됐으면')
    // '않되었을' → '안됐을'
    .replace(/않되었을/g, '안됐을')
    // '않되었으니' → '안됐으니'
    .replace(/않되었으니/g, '안됐으니')
    // '어의없다' → '어이없다'
    .replace(/어의없다/g, '어이없다')
    // '왠지' → '웬지'
    .replace(/왠지/g, '웬지')
    // '왠일' → '웬일'
    .replace(/왠일/g, '웬일')
    // '왠만하면' → '웬만하면'
    .replace(/왠만하면/g, '웬만하면')
    // '왠만한' → '웬만한'
    .replace(/왠만한/g, '웬만한')
    // '왠만해서' → '웬만해서'
    .replace(/왠만해서/g, '웬만해서')
    // '왠만치' → '웬만치'
    .replace(/왠만치/g, '웬만치')
    // '헷갈리다' → '헷갈리다' (헷갈리다/헷갈리다 혼동 방지)
    .replace(/햇갈리다/g, '헷갈리다')
    // '가르치다' → '가르치다' (가르키다/가르치다)
    .replace(/가르키다/g, '가리키다')
    // '틀리다' → '다르다' (틀리다/다르다 혼동)
    .replace(/틀린 점/g, '다른 점')
    // '몇일' → '며칠'
    .replace(/몇일/g, '며칠')
    // '에요' → '예요' (받침 없는 경우)
    .replace(/([가-힣])에요/g, '$1예요')
    // '의외로' → '외외로' (의외로/외외로 혼동)
    .replace(/외외로/g, '의외로')
    // '같이' → '같이' (같이/갔다 혼동)
    .replace(/같이 가다/g, '같이 가다')
    // '그런데' → '근데'
    .replace(/근데/g, '그런데')
    // '어떻게' → '어떡해'
    .replace(/어떡해/g, '어떻게')
    // '않' → '안' (않/안 혼동)
    .replace(/않다/g, '안다')
    // '않되' → '안돼'
    .replace(/않되/g, '안돼')
    // '않됬' → '안됐'
    .replace(/않됬/g, '안됐')
    // '않됬다' → '안됐다'
    .replace(/않됬다/g, '안됐다')
    // '않됬어' → '안됐어'
    .replace(/않됬어/g, '안됐어')
    // '않됬습니다' → '안됐습니다'
    .replace(/않됬습니다/g, '안됐습니다')
    // '않되요' → '안돼요'
    .replace(/않되요/g, '안돼요')
    // '않되서' → '안돼서'
    .replace(/않되서/g, '안돼서')
    // '않되었다' → '안됐다'
    .replace(/않되었다/g, '안됐다')
    // '않되었다고' → '안됐다고'
    .replace(/않되었다고/g, '안됐다고')
    // '않되었다면' → '안됐다면'
    .replace(/않되었다면/g, '안됐다면')
    // '않되었으면' → '안됐으면'
    .replace(/않되었으면/g, '안됐으면')
    // '않되었을' → '안됐을'
    .replace(/않되었을/g, '안됐을')
    // '않되었으니' → '안됐으니'
    .replace(/않되었으니/g, '안됐으니')
    // '왠만치 않다' → '웬만치 않다'
    .replace(/왠만치 않다/g, '웬만치 않다')
    // '왠만치 않으면' → '웬만치 않으면'
    .replace(/왠만치 않으면/g, '웬만치 않으면')
    // '왠만치 않으니' → '웬만치 않으니'
    .replace(/왠만치 않으니/g, '웬만치 않으니')
    // '왠만치 않아서' → '웬만치 않아서'
    .replace(/왠만치 않아서/g, '웬만치 않아서')
    // '왠만치 않으니까' → '웬만치 않으니까'
    .replace(/왠만치 않으니까/g, '웬만치 않으니까')
    // '왠만치 않으니깐' → '웬만치 않으니깐'
    .replace(/왠만치 않으니깐/g, '웬만치 않으니깐')
    // '왠만치 않으니깐요' → '웬만치 않으니깐요'
    .replace(/왠만치 않으니깐요/g, '웬만치 않으니깐요')
    // '왠만치 않으니깐도' → '웬만치 않으니깐도'
    .replace(/왠만치 않으니깐도/g, '웬만치 않으니깐도')
    // '왠만치 않으니깐까지' → '웬만치 않으니깐까지'
    .replace(/왠만치 않으니깐까지/g, '웬만치 않으니깐까지')
    // '왠만치 않으니깐까지도' → '웬만치 않으니깐까지도'
    .replace(/왠만치 않으니깐까지도/g, '웬만치 않으니깐까지도')
    // 추가 맞춤법/오타/관용적 오류 패턴 (방대하게 확장)
    .replace(/어의/g, '어이')
    .replace(/어의없다/g, '어이없다')
    .replace(/틀린말/g, '잘못된 말')
    .replace(/틀린것/g, '잘못된 것')
    .replace(/틀린점/g, '잘못된 점')
    .replace(/같이해/g, '같이 해')
    .replace(/같이갈게/g, '같이 갈게')
    .replace(/같이갈께/g, '같이 갈게')
    .replace(/같이올게/g, '같이 올게')
    .replace(/같이올께/g, '같이 올게')
    .replace(/같이볼게/g, '같이 볼게')
    .replace(/같이볼께/g, '같이 볼게')
    .replace(/같이먹을게/g, '같이 먹을게')
    .replace(/같이먹을께/g, '같이 먹을게')
    .replace(/같이있을게/g, '같이 있을게')
    .replace(/같이있을께/g, '같이 있을게')
    .replace(/같이없을게/g, '같이 없을게')
    .replace(/같이없을께/g, '같이 없을게')
    .replace(/할께/g, '할게')
    .replace(/갈께/g, '갈게')
    .replace(/올께/g, '올게')
    .replace(/볼께/g, '볼게')
    .replace(/먹을께/g, '먹을게')
    .replace(/있을께/g, '있을게')
    .replace(/없을께/g, '없을게')
    .replace(/할껀데/g, '할 건데')
    .replace(/할껀가/g, '할 건가')
    .replace(/할껄/g, '할 걸')
    .replace(/할껏/g, '할 것')
    .replace(/할껏같다/g, '할 것 같다')
    .replace(/할껏같은/g, '할 것 같은')
    .replace(/할껏같이/g, '할 것 같이')
    .replace(/할껏같으면/g, '할 것 같으면')
    .replace(/할껏같아서/g, '할 것 같아서')
    .replace(/할껏같으니/g, '할 것 같으니')
    .replace(/할껏같으니까/g, '할 것 같으니까')
    .replace(/할껏같으니깐/g, '할 것 같으니깐')
    .replace(/할껏같으니깐요/g, '할 것 같으니깐요')
    .replace(/할껏같으니깐도/g, '할 것 같으니깐도')
    .replace(/할껏같으니깐까지/g, '할 것 같으니깐까지')
    .replace(/할껏같으니깐까지도/g, '할 것 같으니깐까지도')
    .replace(/않아요/g, '안 해요')
    .replace(/않아/g, '안 해')
    .replace(/않았어요/g, '안 했어요')
    .replace(/않았어/g, '안 했어')
    .replace(/않을게요/g, '안 할게요')
    .replace(/않을게/g, '안 할게')
    .replace(/않을께/g, '안 할게')
    .replace(/않을께요/g, '안 할게요')
    .replace(/않을껀데/g, '안 할 건데')
    .replace(/않을껀가/g, '안 할 건가')
    .replace(/않을껄/g, '안 할 걸')
    .replace(/않을껏/g, '안 할 것')
    .replace(/않을껏같다/g, '안 할 것 같다')
    .replace(/않을껏같은/g, '안 할 것 같은')
    .replace(/않을껏같이/g, '안 할 것 같이')
    .replace(/않을껏같으면/g, '안 할 것 같으면')
    .replace(/않을껏같아서/g, '안 할 것 같아서')
    .replace(/않을껏같으니/g, '안 할 것 같으니')
    .replace(/않을껏같으니까/g, '안 할 것 같으니까')
    .replace(/않을껏같으니깐/g, '안 할 것 같으니깐')
    .replace(/않을껏같으니깐요/g, '안 할 것 같으니깐요')
    .replace(/않을껏같으니깐도/g, '안 할 것 같으니깐도')
    .replace(/않을껏같으니깐까지/g, '안 할 것 같으니깐까지')
    .replace(/않을껏같으니깐까지도/g, '안 할 것 같으니깐까지도')
    .replace(/어떻해/g, '어떻게')
    .replace(/이렇다/g, '이러하다')
    .replace(/그렇다/g, '그러하다')
    .replace(/않되다/g, '안 되다')
    .replace(/않된다/g, '안 된다')
    .replace(/않되었/g, '안 되었')
    .replace(/않되게/g, '안 되게')
    .replace(/않되니/g, '안 되니')
    .replace(/않되니까/g, '안 되니까')
    .replace(/않되니깐/g, '안 되니깐')
    .replace(/않되니깐요/g, '안 되니깐요')
    .replace(/않되니깐도/g, '안 되니깐도')
    .replace(/않되니깐까지/g, '안 되니깐까지')
    .replace(/않되니깐까지도/g, '안 되니깐까지도')
    .replace(/않되었니/g, '안 되었니')
    .replace(/않되었으니/g, '안 되었으니')
    .replace(/않되었으니까/g, '안 되었으니까')
    .replace(/않되었으니깐/g, '안 되었으니깐')
    .replace(/않되었으니깐요/g, '안 되었으니깐요')
    .replace(/않되었으니깐도/g, '안 되었으니깐도')
    .replace(/않되었으니깐까지/g, '안 되었으니깐까지')
    .replace(/않되었으니깐까지도/g, '안 되었으니깐까지도')
    .replace(/햇빛/g, '햇볕')
    .replace(/설겆이/g, '설거지')
    .replace(/들어나다/g, '드러나다')
    .replace(/되려/g, '도리어')
    .replace(/내노라하다/g, '내로라하다')
    .replace(/왠일이야/g, '웬일이야')
    .replace(/왠만큼/g, '웬만큼')
    .replace(/왠지모르게/g, '웬지 모르게')
    .replace(/왠지모르겠어/g, '웬지 모르겠어')
    .replace(/왠지모르겠다/g, '웬지 모르겠다')
    .replace(/왠지모르겠네/g, '웬지 모르겠네')
    .replace(/왠지모르겠지만/g, '웬지 모르겠지만')
    .replace(/왠지모르겠으나/g, '웬지 모르겠으나')
    .replace(/왠지모르겠으면서/g, '웬지 모르겠으면서')
    .replace(/왠지모르겠으니/g, '웬지 모르겠으니')
    .replace(/왠지모르겠으니까/g, '웬지 모르겠으니까')
    .replace(/왠지모르겠으니깐/g, '웬지 모르겠으니깐')
    .replace(/왠지모르겠으니깐요/g, '웬지 모르겠으니깐요')
    .replace(/왠지모르겠으니깐도/g, '웬지 모르겠으니깐도')
    .replace(/왠지모르겠으니깐까지/g, '웬지 모르겠으니깐까지')
    .replace(/왠지모르겠으니깐까지도/g, '웬지 모르겠으니깐까지도')
    .replace(/왠지모르겠어도/g, '웬지 모르겠어도')
    .replace(/왠지모르겠어서/g, '웬지 모르겠어서')
    .replace(/왠지모르겠으면서도/g, '웬지 모르겠으면서도')
    // --- 일반적으로 자주 틀리는 맞춤법/띄어쓰기/오타 추가 ---
    .replace(/왠지모를/g, '웬지 모를')
    .replace(/왠지모를/g, '웬지 모를')
    .replace(/왠지모르겠/g, '웬지 모르겠')
    .replace(/왠지모르니/g, '웬지 모르니')
    .replace(/왠지모르니까/g, '웬지 모르니까')
    .replace(/왠지모르겠지/g, '웬지 모르겠지')
    .replace(/왠지모르겠네/g, '웬지 모르겠네')
    .replace(/왠지모르겠어/g, '웬지 모르겠어')
    .replace(/왠지모르겠다/g, '웬지 모르겠다')
    .replace(/왠지모르겠지만/g, '웬지 모르겠지만')
    .replace(/왠지모르겠으나/g, '웬지 모르겠으나')
    .replace(/왠지모르겠으면서/g, '웬지 모르겠으면서')
    .replace(/왠지모르겠으니/g, '웬지 모르겠으니')
    .replace(/왠지모르겠으니까/g, '웬지 모르겠으니까')
    .replace(/왠지모르겠으니깐/g, '웬지 모르겠으니깐')
    .replace(/왠지모르겠으니깐요/g, '웬지 모르겠으니깐요')
    .replace(/왠지모르겠으니깐도/g, '웬지 모르겠으니깐도')
    .replace(/왠지모르겠으니깐까지/g, '웬지 모르겠으니깐까지')
    .replace(/왠지모르겠으니깐까지도/g, '웬지 모르겠으니깐까지도')
    // 자주 틀리는 띄어쓰기
    .replace(/이랑같이/g, '이랑 같이')
    .replace(/하고같이/g, '하고 같이')
    .replace(/같이가자/g, '같이 가자')
    .replace(/같이먹자/g, '같이 먹자')
    .replace(/같이살자/g, '같이 살자')
    .replace(/같이놀자/g, '같이 놀자')
    .replace(/같이일하자/g, '같이 일하자')
    .replace(/같이공부하자/g, '같이 공부하자')
    .replace(/같이앉자/g, '같이 앉자')
    .replace(/같이걷자/g, '같이 걷자')
    .replace(/같이타자/g, '같이 타자')
    .replace(/같이보자/g, '같이 보자')
    .replace(/같이듣자/g, '같이 듣자')
    .replace(/같이보내자/g, '같이 보내자')
    .replace(/같이살펴보자/g, '같이 살펴보자')
    // 자주 틀리는 오타
    .replace(/왠지안/g, '웬지 안')
    .replace(/왠지잘/g, '웬지 잘')
    .replace(/왠지못/g, '웬지 못')
    .replace(/왠지더/g, '웬지 더')
    .replace(/왠지덜/g, '웬지 덜')
    .replace(/왠지많이/g, '웬지 많이')
    .replace(/왠지적게/g, '웬지 적게')
    // 관용적 오류
    .replace(/일일이/g, '일일이') // (일일히 → 일일이)
    .replace(/왠만치않다/g, '웬만치 않다')
    .replace(/왠만치않으면/g, '웬만치 않으면')
    .replace(/왠만치않으니/g, '웬만치 않으니')
    .replace(/왠만치않아서/g, '웬만치 않아서')
    .replace(/왠만치않으니까/g, '웬만치 않으니까')
    .replace(/왠만치않으니깐/g, '웬만치 않으니깐')
    .replace(/왠만치않으니깐요/g, '웬만치 않으니깐요')
    .replace(/왠만치않으니깐도/g, '웬만치 않으니깐도')
    .replace(/왠만치않으니깐까지/g, '웬만치 않으니깐까지')
    .replace(/왠만치않으니깐까지도/g, '웬만치 않으니깐까지도')
    // 기타 자주 틀리는 표현
    .replace(/왠지모르겠음/g, '웬지 모르겠음')
    .replace(/왠지모르겠음요/g, '웬지 모르겠음요')
    .replace(/왠지모르겠음에도/g, '웬지 모르겠음에도')
    .replace(/왠지모르겠음이라/g, '웬지 모르겠음이라')
    .replace(/왠지모르겠음이/g, '웬지 모르겠음이')
    .replace(/왠지모르겠음도/g, '웬지 모르겠음도')
    .replace(/왠지모르겠음까지/g, '웬지 모르겠음까지')
    .replace(/왠지모르겠음까지도/g, '웬지 모르겠음까지도')
    // 띄어쓰기 오류
    .replace(/뭐라고할/g, '뭐라고 할')
    .replace(/뭐라고했/g, '뭐라고 했')
    .replace(/뭐라고하는/g, '뭐라고 하는')
    .replace(/뭐라고하는지/g, '뭐라고 하는지')
    .replace(/뭐라고할지/g, '뭐라고 할지')
    .replace(/뭐라고할까/g, '뭐라고 할까')
    .replace(/뭐라고할게/g, '뭐라고 할게')
    .replace(/뭐라고할께/g, '뭐라고 할게')
    .replace(/뭐라고했는지/g, '뭐라고 했는지')
    .replace(/뭐라고했길래/g, '뭐라고 했길래')
    .replace(/뭐라고했길래/g, '뭐라고 했길래')
    .replace(/뭐라고했더라/g, '뭐라고 했더라')
    .replace(/뭐라고했었/g, '뭐라고 했었')
    .replace(/뭐라고했으니/g, '뭐라고 했으니')
    .replace(/뭐라고했으니까/g, '뭐라고 했으니까')
    .replace(/뭐라고했으니깐/g, '뭐라고 했으니깐')
    .replace(/뭐라고했으니깐요/g, '뭐라고 했으니깐요')
    .replace(/뭐라고했으니깐도/g, '뭐라고 했으니깐도')
    .replace(/뭐라고했으니깐까지/g, '뭐라고 했으니깐까지')
    .replace(/뭐라고했으니깐까지도/g, '뭐라고 했으니깐까지도')
    // 기타 자주 틀리는 표현
    .replace(/왠지모르겠음/g, '웬지 모르겠음')
    .replace(/왠지모르겠음요/g, '웬지 모르겠음요')
    .replace(/왠지모르겠음에도/g, '웬지 모르겠음에도')
    .replace(/왠지모르겠음이라/g, '웬지 모르겠음이라')
    .replace(/왠지모르겠음이/g, '웬지 모르겠음이')
    .replace(/왠지모르겠음도/g, '웬지 모르겠음도')
    .replace(/왠지모르겠음까지/g, '웬지 모르겠음까지')
    .replace(/왠지모르겠음까지도/g, '웬지 모르겠음까지도')
    // 오타
    .replace(/왠지모르겠슴/g, '웬지 모르겠음')
    .replace(/왠지모르겠슴요/g, '웬지 모르겠음요')
    .replace(/왠지모르겠슴에도/g, '웬지 모르겠음에도')
    .replace(/왠지모르겠슴이라/g, '웬지 모르겠음이라')
    .replace(/왠지모르겠슴이/g, '웬지 모르겠음이')
    .replace(/왠지모르겠슴도/g, '웬지 모르겠음도')
    .replace(/왠지모르겠슴까지/g, '웬지 모르겠음까지')
    .replace(/왠지모르겠슴까지도/g, '웬지 모르겠음까지도')
    // --- 사용자 요청: 자주 틀리는 맞춤법/띄어쓰기/오타/관용적 오류 추가 ---
    .replace(/되요/g, '돼요')
    .replace(/되서/g, '돼서')
    .replace(/잘되서/g, '잘돼서')
    .replace(/안되다/g, '안 되다')
    .replace(/할수있다/g, '할 수 있다')
    .replace(/될수있다/g, '될 수 있다')
    .replace(/너 뿐/g, '너뿐')
    .replace(/할뿐이다/g, '할 뿐이다')
    .replace(/모를줄 알았다/g, '모를 줄 알았다')
    .replace(/올것같다/g, '올 것 같다')
    .replace(/정답을 맞추다/g, '정답을 맞히다')
    .replace(/시계를 맞히다/g, '시계를 맞추다')
    .replace(/잠깐 들리다/g, '잠깐 들르다')
    .replace(/소리가 들르다/g, '소리가 들리다')
    .replace(/이쁘다/g, '예쁘다')
    .replace(/설레이다/g, '설레다')
    .replace(/아무렇치 않다/g, '아무렇지 않다')
    .replace(/([0-9]+)\s*월/g, '$1월')
    .replace(/([0-9]+)\s*일/g, '$1일')
    .replace(/될려/g, '되려')
    .replace(/아무렇지않다/g, '아무렇지 않다')
    .replace(/별일없다/g, '별일 없다')
    .replace(/잘됐다/g, '잘 됐다')
    .replace(/잘되다/g, '잘 되다')
    .replace(/잘될거야/g, '잘 될 거야')
    .replace(/잘될것/g, '잘 될 것')
    .replace(/잘될수/g, '잘 될 수')
    .replace(/잘될지/g, '잘 될지')
    .replace(/할것이다/g, '할 것이다')
    .replace(/할수있을까/g, '할 수 있을까')
    .replace(/할수있어요/g, '할 수 있어요')
    .replace(/할수있을것/g, '할 수 있을 것')
    .replace(/될것이다/g, '될 것이다')
    .replace(/될수있을까/g, '될 수 있을까')
    .replace(/될수있어요/g, '될 수 있어요')
    .replace(/될수있을것/g, '될 수 있을 것')
    .replace(/될것같다/g, '될 것 같다')
    .replace(/될것같아요/g, '될 것 같아요')
    .replace(/될것같으면/g, '될 것 같으면')
    .replace(/될것같은/g, '될 것 같은')
    .replace(/될것같이/g, '될 것 같이')
    .replace(/될것같아서/g, '될 것 같아서')
    .replace(/될것같으니/g, '될 것 같으니')
    .replace(/될것같으니까/g, '될 것 같으니까')
    .replace(/될것같으니깐/g, '될 것 같으니깐')
    .replace(/될것같으니깐요/g, '될 것 같으니깐요')
    .replace(/될것같으니깐도/g, '될 것 같으니깐도')
    .replace(/될것같으니깐까지/g, '될 것 같으니깐까지')
    .replace(/될것같으니깐까지도/g, '될 것 같으니깐까지도')
    .replace(/안돼요/g, '안 돼요')
    .replace(/안됐어요/g, '안 됐어요')
    .replace(/안됐어/g, '안 됐어')
    .replace(/안됐습니다/g, '안 됐습니다')
    .replace(/안될거야/g, '안 될 거야')
    .replace(/안될것/g, '안 될 것')
    .replace(/안될수/g, '안 될 수')
    .replace(/안될지/g, '안 될지')
    .replace(/할것/g, '할 것')
.replace(/될것/g, '될 것')
.replace(/올것/g, '올 것')
.replace(/갈것/g, '갈 것')
.replace(/볼것/g, '볼 것')
.replace(/먹을것/g, '먹을 것')
.replace(/할수/g, '할 수')
.replace(/될수/g, '될 수')
.replace(/올수/g, '올 수')
.replace(/갈수/g, '갈 수')
.replace(/볼수/g, '볼 수')
.replace(/먹을수/g, '먹을 수')
.replace(/하는중/g, '하는 중')
.replace(/공사중/g, '공사 중')
.replace(/할뿐/g, '할 뿐')
.replace(/될뿐/g, '될 뿐')
.replace(/한달만/g, '한 달만')
.replace(/일년만/g, '일 년만')
.replace(/온지/g, '온 지')
.replace(/떠난지/g, '떠난 지')
.replace(/갈데/g, '갈 데')
.replace(/아픈데/g, '아픈 데')
.replace(/모를줄/g, '모를 줄')
.replace(/갈바/g, '갈 바')
.replace(/그럴바에/g, '그럴 바에')
.replace(/나갈차에/g, '나갈 차에')
.replace(/해보다/g, '해 보다')
.replace(/가보다/g, '가 보다')
.replace(/먹어보다/g, '먹어 보다')
.replace(/만들어주다/g, '만들어 주다')
.replace(/도와주다/g, '도와주다')
.replace(/보고싶다/g, '보고 싶다')
.replace(/먹고싶다/g, '먹고 싶다')
.replace(/자고싶다/g, '자고 싶다')
.replace(/아무렇지않다/g, '아무렇지 않다')
.replace(/별일없다/g, '별일 없다')
.replace(/어쩔수없다/g, '어쩔 수 없다')
.replace(/상관없다/g, '상관 없다')
.replace(/그럴수있다/g, '그럴 수 있다')
.replace(/같이하다/g, '같이 하다')
.replace(/뭐라고할/g, '뭐라고 할')
.replace(/뭐라고했/g, '뭐라고 했')
.replace(/됬/g, '됐')
.replace(/되요/g, '돼요')
.replace(/되서/g, '돼서')
.replace(/안되/g, '안 돼')
.replace(/않돼/g, '안돼')
.replace(/않된다/g, '안된다')
.replace(/않할/g, '안 할')
.replace(/할께/g, '할게')
.replace(/갈께/g, '갈게')
.replace(/볼께/g, '볼게')
.replace(/왠일/g, '웬일')
.replace(/왠만하면/g, '웬만하면')
.replace(/왠만큼/g, '웬만큼')
.replace(/어의없다/g, '어이없다')
.replace(/어의가없다/g, '어이가 없다')
.replace(/몇일/g, '며칠')
.replace(/설겆이/g, '설거지')
.replace(/설레이다/g, '설레다')
.replace(/오랫만/g, '오랜만')
.replace(/금새/g, '금세')
.replace(/바램/g, '바람')
.replace(/들어나다/g, '드러나다')
.replace(/내노라하는/g, '내로라하는')
.replace(/이쁘다/g, '예쁘다')
.replace(/아뭏든/g, '아무튼')
.replace(/어떻해/g, '어떡해')
.replace(/가르키다/g, '가리키다')
.replace(/꼼꼼이/g, '꼼꼼히')
.replace(/틈틈이/g, '틈틈이')
.replace(/할라고/g, '하려고')
.replace(/볼라고/g, '보려고')
.replace(/할껀데/g, '할 건데')
.replace(/갈껀데/g, '갈 건데')
.replace(/할껄/g, '할 걸')
.replace(/(\d+)\s*년/g, '$1년')
.replace(/(\d+)\s*월/g, '$1월')
.replace(/(\d+)\s*일/g, '$1일')
.replace(/(\d+)\s*시/g, '$1시')
.replace(/(\d+)\s*분/g, '$1분')
.replace(/(\d+)\s*초/g, '$1초')
.replace(/(\d+)\s*개/g, '$1개')
.replace(/(\d+)\s*명/g, '$1명')
.replace(/할께요/g, '할게요')
.replace(/될께요/g, '될게요')
.replace(/갈께요/g, '갈게요')
.replace(/볼께요/g, '볼게요')
.replace(/할꺼야/g, '할 거야')
.replace(/될꺼야/g, '될 거야')
.replace(/갈꺼야/g, '갈 거야')
.replace(/할껀데/g, '할 건데')
.replace(/될껀데/g, '될 건데')
.replace(/갈껀데/g, '갈 건데')
.replace(/라던지/g, '라든지')
.replace(/~하던지/g, '~하든지')
.replace(/어따대고/g, '얻다 대고')
.replace(/어따써/g, '얻다 써')
.replace(/어따가/g, '얻다가')
.replace(/깨끗히/g, '깨끗이')
.replace(/꼼꼼히/g, '꼼꼼히')
.replace(/솔찍히/g, '솔직히')
.replace(/오랫동안/g, '오랫동안')
.replace(/그동안/g, '그동안')
.replace(/~읍니다/g, '~습니다')
.replace(/~했읍니다/g, '~했습니다')
.replace(/~ㄹ런지/g, '~ㄹ는지')
.replace(/~할련지/g, '~할는지')
.replace(/김치찌게/g, '김치찌개')
.replace(/육계장/g, '육개장')
.replace(/곱배기/g, '곱빼기')
.replace(/빈털털이/g, '빈털터리')
.replace(/오뚜기/g, '오뚝이')
.replace(/통채로/g, '통째로')
.replace(/구지/g, '굳이')
.replace(/오랫만에/g, '오랜만에')
.replace(/아뭏든/g, '아무튼')
.replace(/~ㄹ려구/g, '~려고')
.replace(/했데/g, '했대')
.replace(/그렇다더라/g, '그렇다더라')
.replace(/~더라구요/g, '~더라고요')
.replace(/~할려고/g, '~하려고')
.replace(/해볼려고/g, '해보려고')
.replace(/만날려고/g, '만나려고')
.replace(/닥달하다/g, '닦달하다')
.replace(/뒤치닥거리/g, '뒤치다꺼리')
.replace(/널부러지다/g, '널브러지다')
.replace(/찌뿌둥하다/g, '찌뿌드드하다')
.replace(/주구장창/g, '주야장천')
.replace(/희안하다/g, '희한하다')
.replace(/궁시렁거리다/g, '구시렁거리다')
.replace(/뒤집어씌우다/g, '뒤집어씌우다')
.replace(/걸맞는/g, '걸맞은')
.replace(/지난 번/g, '지난번')
.replace(/이번 만큼은/g, '이번만큼은')
.replace(/그 외/g, '그외')
.replace(/뿐만아니라/g, '뿐만 아니라')
.replace(/이외에도/g, '이외에도')
.replace(/그럴싸하다/g, '그럴싸하다')
.replace(/몇일 몇일/g, '며칠 며칠')
.replace(/몇일동안/g, '며칠 동안')
.replace(/몇일만에/g, '며칠 만에')
.replace(/몇일전/g, '며칠 전')
.replace(/하지마/g, '하지 마')
.replace(/가지마/g, '가지 마')
.replace(/보지마/g, '보지 마')
.replace(/먹지마/g, '먹지 마')
.replace(/는 커녕/g, '는커녕')
.replace(/을 막론하고/g, '을 막론하고')
.replace(/~ㄹ 수록/g, '~ㄹ수록')
.replace(/~할 수록/g, '~할수록')
.replace(/~갈 수록/g, '~갈수록')
.replace(/최소한/g, '최소한')
.replace(/최대한/g, '최대한')
.replace(/막상/g, '막상')
.replace(/오손도손/g, '오순도순')
.replace(/핼쑥하다/g, '해쓱하다')
.replace(/있슴/g, '있음')
.replace(/없슴/g, '없음')
.replace(/했슴/g, '했음')
.replace(/~읍니다/g, '습니다')
.replace(/~읍시다/g, 'ㅂ시다')
.replace(/안밖/g, '안팎')
.replace(/위아래/g, '위아래')
.replace(/숫놈/g, '수놈')
.replace(/숫소/g, '수소')
.replace(/숫캐/g, '수캐')
.replace(/암놈/g, '암놈')
.replace(/암캐/g, '암캐')
.replace(/윗층/g, '위층')
.replace(/아랫층/g, '아래층')
.replace(/뒷편/g, '뒤편')
.replace(/뒷쪽/g, '뒤쪽')
.replace(/오랜시간/g, '오랜 시간')
.replace(/한두번/g, '한두 번')
.replace(/한두개/g, '한두 개')
.replace(/한입/g, '한입')
.replace(/첫번째/g, '첫 번째')
.replace(/두번째/g, '두 번째')
.replace(/세번째/g, '세 번째')
.replace(/네번째/g, '네 번째')
.replace(/다섯번째/g, '다섯 번째')
.replace(/안절부절못하다/g, '안절부절못하다')
.replace(/허구헛날/g, '허구한 날')
.replace(/이 자리를 빌어/g, '이 자리를 빌려')
.replace(/~던가/g, '~던가')
.replace(/~던데/g, '~던데')
.replace(/단언컨데/g, '단언컨대')
.replace(/어따써/g, '얻다 써')
.replace(/오지랍/g, '오지랖')
.replace(/넓직하다/g, '널찍하다')
.replace(/널판지/g, '널빤지')
.replace(/절대절명/g, '절체절명')
.replace(/풍지박산/g, '풍비박산')
.replace(/야밤도주/g, '야반도주')
.replace(/주책이다/g, '주책이다')
.replace(/주책맞다/g, '주책맞다')
.replace(/원상복귀/g, '원상복구')
.replace(/골치꺼리/g, '골칫거리')
.replace(/희노애락/g, '희로애락')
.replace(/사그러들다/g, '수그러들다')
.replace(/눈쌀/g, '눈살')
.replace(/눈꼽/g, '눈곱')
.replace(/콧배기/g, '콧배기')
.replace(/개발새발/g, '괴발개발')
.replace(/에요/g, '예요') // 매우 주의: 문맥에 따라 오류 많음
.replace(/인터넷 상에서/g, '인터넷상에서')
.replace(/관계 상/g, '관계상')
.replace(/온라인 상/g, '온라인상')
.replace(/천원 짜리/g, '천원짜리')
.replace(/만원 짜리/g, '만원짜리')
.replace(/~함으로서/g, '~함으로써')
.replace(/~므로서/g, '~으로써')
.replace(/매 시간/g, '매시간')
.replace(/전 국민/g, '전국민')
.replace(/전 세계/g, '전 세계') // '전 세계'는 띄어쓰기가 맞음
.replace(/~할 바에야/g, '~할 바에야')
.replace(/~할 지언정/g, '~할지언정')
.replace(/~할 참이다/g, '~할 참이다')
.replace(/~할 겸/g, '~할 겸')
.replace(/~ㄹ텐데/g, '~ㄹ 텐데')
.replace(/~할텐데/g, '~할 텐데')
.replace(/~갈텐데/g, '~갈 텐데')
.replace(/~올텐데/g, '~올 텐데')
.replace(/~볼텐데/g, '~볼 텐데')
.replace(/~먹을텐데/g, '~먹을 텐데')
.replace(/~있을텐데/g, '~있을 텐데')
.replace(/~없을텐데/g, '~없을 텐데')
.replace(/~했을텐데/g, '~했을 텐데')
.replace(/어쨋든/g, '어쨌든')
.replace(/여지껏/g, '여태껏')
.replace(/그리고나서/g, '그러고 나서')
.replace(/이럴려고/g, '이러려고')
.replace(/저럴려고/g, '저러려고')
.replace(/그럴려고/g, '그러려고')
.replace(/하는둥마는둥/g, '하는 둥 마는 둥')
.replace(/보는둥마는둥/g, '보는 둥 마는 둥')
.replace(/먹는둥마는둥/g, '먹는 둥 마는 둥')
.replace(/~는바람에/g, '는 바람에')
.replace(/~ㄹ지라도/g, 'ㄹ지라도')
.replace(/~할지라도/g, '할지라도')
.replace(/코날/g, '콧날')
.replace(/바다물/g, '바닷물')
.replace(/나무가지/g, '나뭇가지')
.replace(/아래집/g, '아랫집')
.replace(/뒤골목/g, '뒷골목')
.replace(/촛불/g, '촛불')
.replace(/애기/g, '아기')
.replace(/메세지/g, '메시지')
.replace(/에어콘/g, '에어컨')
.replace(/콘트롤/g, '컨트롤')
.replace(/컨셉/g, '콘셉트')
.replace(/케잌/g, '케이크')
.replace(/쥬스/g, '주스')
.replace(/쉅다/g, '쉽다')
.replace(/안성맞춤이다/g, '안성맞춤이다')
.replace(/헤메다/g, '헤매다')
.replace(/바꼈다/g, '바뀌었다')
.replace(/바꼈어/g, '바뀌었어')
.replace(/갈수록/g, '갈수록')
.replace(/알다시피/g, '알다시피')
.replace(/보시다시피/g, '보시다시피')
.replace(/말씀드리다/g, '말씀드리다')
.replace(/생각컨대/g, '생각건대')
.replace(/바라컨대/g, '바라건대')
.replace(/초콜렛/g, '초콜릿')
.replace(/카라멜/g, '캐러멜')
.replace(/도너츠/g, '도넛')
.replace(/소세지/g, '소시지')
.replace(/런닝/g, '러닝')
.replace(/네비게이션/g, '내비게이션')
.replace(/바베큐/g, '바비큐')
.replace(/리더쉽/g, '리더십')
.replace(/멤버쉽/g, '멤버십')
.replace(/케찹/g, '케첩')
.replace(/컨텐츠/g, '콘텐츠')
.replace(/카폐/g, '카페')
.replace(/가디건/g, '카디건')
.replace(/판타지/g, '판타지')
.replace(/화이팅/g, '파이팅')
.replace(/만두국/g, '만둣국')
.replace(/순대국/g, '순댓국')
.replace(/북어국/g, '북엇국')
.replace(/장마비/g, '장맛비')
.replace(/머릿말/g, '머리말')
.replace(/인삿말/g, '인사말')
.replace(/댓가/g, '대가')
.replace(/윗쪽/g, '위쪽')
.replace(/아랫쪽/g, '아래쪽')
.replace(/뒤처리/g, '뒤처리')
.replace(/하는게/g, '하는 게')
.replace(/보는게/g, '보는 게')
.replace(/가는게/g, '가는 게')
.replace(/먹는게/g, '먹는 게')
.replace(/~ㄹ걸/g, '~ㄹ 걸')
.replace(/할걸/g, '할 걸')
.replace(/갈걸/g, '갈 걸')
.replace(/볼걸/g, '볼 걸')
.replace(/먹을걸/g, '먹을 걸')
.replace(/서슴치/g, '서슴지')
.replace(/익숙치/g, '익숙지')
.replace(/일부로/g, '일부러')
.replace(/하마트면/g, '하마터면')
.replace(/요세/g, '요새')
.replace(/귀뜸/g, '귀띔')
.replace(/낭떨어지/g, '낭떠러지')
.replace(/꺼림직하다/g, '께름칙하다')
.replace(/건들이다/g, '건드리다')
.replace(/짜집기/g, '짜깁기')
.replace(/통털어/g, '통틀어')
.replace(/윗어른/g, '웃어른')
.replace(/오랜동안/g, '오랫동안')
.replace(/글자그대로/g, '글자 그대로')
.replace(/천상여자/g, '천상 여자')
.replace(/~함으로써/g, '으로써')
.replace(/결제 바랍니다/g, '결재 바랍니다')
.replace(/결제 부탁드립니다/g, '결재 부탁드립니다')
.replace(/결제 올립니다/g, '결재 올립니다')
.replace(/서류 결제/g, '서류 결재')
.replace(/역활/g, '역할')
.replace(/효율성 재고/g, '효율성 제고')
.replace(/경쟁력 재고/g, '경쟁력 제고')
.replace(/유래없는/g, '유례없는')
.replace(/보고드립니다/g, '보고 드립니다')
.replace(/문의드립니다/g, '문의 드립니다')
.replace(/회신드립니다/g, '회신 드립니다')
.replace(/연락드립니다/g, '연락 드립니다')
.replace(/참조바랍니다/g, '참조 바랍니다')
.replace(/확인바랍니다/g, '확인 바랍니다')
.replace(/회신바랍니다/g, '회신 바랍니다')
.replace(/협조바랍니다/g, '협조 바랍니다')
.replace(/첨부파일/g, '첨부 파일')
.replace(/엑셀파일/g, '엑셀 파일')
.replace(/업무상/g, '업무상')
.replace(/금일부로/g, '금일부로')
.replace(/익일부로/g, '익일부로')
.replace(/년도/g, '연도')
.replace(/년차/g, '연차')
.replace(/회의녹/g, '회의록')
.replace(/두루뭉실하게/g, '두루뭉술하게')
.replace(/프리젠테이션/g, '프레젠테이션')
.replace(/프로잭트/g, '프로젝트')
.replace(/워크샵/g, '워크숍')
.replace(/컴펌/g, '컨펌')
.replace(/아젠다/g, '아젠다')
.replace(/구좌/g, '계좌')
.replace(/수순을 밟다/g, '수순을 밟다')
.replace(/유념하시기/g, '유념하시기')
.replace(/일절/g, '일체')
.replace(/일체 없음/g, '일절 없음')
.replace(/대외 비/g, '대외비')
.replace(/일괄처리/g, '일괄 처리');
} 