openapi: 3.0.0
info:
  title: Service Messenger API
  version: 1.0.0
  description: |
    Service Messenger 백엔드 API 명세 (Swagger)
    - 인증/권한, 채팅, 게시판, 멤버 관리 등 주요 엔드포인트 예시 포함
    - 실제 엔드포인트/스키마는 구현에 따라 확장 필요

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /messenger/rooms:
    post:
      summary: 채팅방 생성
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 성공
    get:
      summary: 채팅방 목록 조회
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 성공
  /messenger/rooms/{roomId}/members/{userId}/role:
    patch:
      summary: 채팅방 멤버 역할 변경
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newRole:
                  type: string
      responses:
        '200':
          description: 성공
  /board/boards/{boardId}/members:
    post:
      summary: 게시판 멤버 초대
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: 성공
# ... (추가 엔드포인트는 구현에 따라 확장) 